### ISSUE TITLE
Consider removing functions.php autoloading

### ISSUE THREAD

**Issue by frederikbosch** [DaveRandom/LibDNS#15]
Since 'files' are always loaded every time you use 'vendor/autoload.php' you should only use in case you for sure that they are *always* needed. Since this is not the case, use ```require_once``` when you are calling the functions inside `functions.php`.

p.s. nice lib!

**Comment by kelunik** [comment]
I don't agree there. No library function should ever require a manual `require_once`. It could, however, be moved to a class as static method.

**Comment by frederikbosch** [comment]
@kelunik See #16

**Comment by frederikbosch** [comment]
I replaced the method for a value object (NormalizedLabel). So no `require_once` which ugly indeed.

**Comment by frederikbosch** [comment]
@kelunik Are you perhaps, just like me exploring how the landscape of DNS libaries is looking like in PHP? And if you are, maybe you are coming to the came conclusions as I do?

**Comment by kelunik** [comment]
@frederikbosch No, I'm not exploring the landscape. LibDNS is the main component behind [`amphp/dns`](https://github.com/amphp/dns) and that specific method has been added due to my request. As LibDNS 2.0.0 isn't released yet, [we copied it](https://github.com/amphp/uri/blob/63b89f8c838f24f21f661ac6dcb282fe50a69171/src/functions.php#L30-L53). Originally, @DaveRandom wanted to do the rewrite for `amphp/dns`, but now @trowski and I did it.

**Comment by DaveRandom** [comment]
In a composer-based environment, this is a total non-issue, because it's hidden for the application with the include of `autoload.php`. Especially with opcache the performance impact is almost nil, even in a completely uncached environment the cost is measured in microseconds.

I do not want to put standalone functions in classes, as this simply creates clutter - as doesn't actually avoid any includes.

The upcoming [version 3](https://github.com/DaveRandom/LibDNS/tree/dev/v3) has dropped the IDN function (or more accurately it has been moved upstream to https://github.com/DaveRandom/NetworkPrimitives) but has introduced new standalone functions. Moving these to a class will either create clutter or put them all into a `Utils` class, which gains you nothing.
